// Implement a function, called `countBy` with the following signature
// This functions works the same way as `groupBy` - keys are generated by `countingFunction`,
// but the values are just the count of items for the given key (Instead of array of values, like `groupBy`)

function countBy (countingFunction, arr) {

}

const students = [
    { 'name': 'Daniel Taskoff', 'course': 'Frontend JavaScript' },
    { 'name': 'Elena Jeleva', 'course': 'Programming 101' },
    { 'name': 'Luboslava Dimitrova', 'course': 'Frontend JavaScript' },
    { 'name': 'Anton Antonov', 'course': 'Core Java' },
    { 'name': 'Nikola Dichev', 'course': 'Core Java' }
];

console.assert(
    countBy(function(student) {
        return student.course;
    }, students) === {
        'Frontend JavaScript': 2,
        'Programming 101': 1,
        'Core Java': 2
    }
)
