// Group them by!

// Implement a function, called `groupBy` with the following signature
// The function returns an associative array (Objects - `{}` in JavaScript) where the keys are generated by the `groupingFunction`.
// For each key, we keep an array of values from `arr` for which, the `groupingFunction` returns the same key.
// All keys returned must be strings!

function groupBy (groupingFunction, arr) {

};

const students = [
    { 'name': 'Daniel Taskoff', 'course': 'Frontend JavaScript' },
    { 'name': 'Elena Jeleva', 'course': 'Programming 101' },
    { 'name': 'Luboslava Dimitrova', 'course': 'Frontend JavaScript' },
    { 'name': 'Anton Antonov', 'course': 'Core Java' },
    { 'name': 'Nikola Dichev', 'course': 'Core Java' }
];

console.assert(
    groupBy(function (student) {
        return student.course;
    }, students) == {
        'Frontend JavaScript': [
            { name: 'Daniel Taskoff', course: 'Frontend JavaScript' },
            { name: 'Luboslava Dimitrova', course: 'Frontend JavaScript' }
        ],
        'Programming 101': [
            { name: 'Elena Jeleva', course: 'Programming 101' }
        ],
        'Core Java': [
            { name: 'Anton Antonov', course: 'Core Java' },
            { name: 'Nikola Dichev', course: 'Core Java' }
        ]
    }
);
